version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-stretch
    branches:
      only:
        - feature/ci
    steps:
      - checkout
      - run: touch ./test.txt
      - deploy:
          name: deploy
          command: |
            rsync -ave ssh ./test.txt campenco@vps0.campen.co
