version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-stretch
    branches:
      only:
        - feature/ci
    steps:
      - checkout
      - ls -l .
#      - deploy:
#          name: deploy
#          command: |
#            rsync -ave ssh
