version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-stretch
    branches:
      only:
        - feature/ci
    steps:
      - checkout
      - run: sudo apt-get install -y rsync
      - run: |
          mkdir ./test
          echo "hello world" > ./test/test.txt
      - deploy:
          name: deploy
          command: |
            rsync -ave ssh ./test/ campenco@vps0.campen.co:/home/campenco/test/
