version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-stretch
    branches:
      only:
        - feature/vagrant
    steps:
      - checkout
      - run: sudo apt-get install -y rsync
      - run: ls .
#      - deploy:
#          name: deploy
#          command: rsync -ave ssh ./test/ campenco@vps0.campen.co:/home/campenco/test/
