# Generated by Django 2.1.3 on 2018-11-24 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_publicationspage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationspage',
            name='publications',
        ),
    ]
