---
- name: Update APT cache
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: Install python{{ python_version_number }}
  apt:
    name: "python{{ python_version_number }}"
    state: present

- name: Install python3-pip
  apt:
    name: python3-pip

- name: Install virtualenv
  pip:
    name: virtualenv
    executable: pip3
    state: present
