---
- hosts: development
  become: yes
  become_method: sudo
  roles:
    - ubuntu
    - python
    - postgres
    - flask
    - supervisor
    - uwsgi
    - nginx

- hosts: production
  remote_user: richardcampendotcom
  roles:
    - python
    - flask
    - uwsgi
